---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "systemdevformations/docker-systemd:almalinux-10"
    pre_build_image: true
    privileged: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_connection: docker
        ansible_remote_tmp: /tmp
        ansible_pipelining: true
verifier:
  name: ansible