---
- name: Gérer et interagir avec un conteneur CentOS 7
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    container_name: mycentos
    # Définir l'interpréteur Python pour les cibles CentOS 7 (Python 2)
    #ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: 1. S'assurer que le conteneur CentOS 7 est démarré
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: docker-systemd:centos-7
        state: started
        # Ajout des dépendances minimales si l'image est trop légère
        command: /bin/bash -c "yum install -y python-minimal && /bin/bash"
        # Le détachement est crucial pour que le conteneur continue de tourner
        detach: true
      register: container_state

    - name: 2. Attendre que le service du conteneur soit prêt
      ansible.builtin.wait_for:
        port: 22 # Ou tout autre port pertinent pour le service
        timeout: 60
      delegate_to: localhost # Cette tâche doit s'exécuter sur le contrôleur
      when: container_state.changed

    - name: 3. Exécuter une commande à l'intérieur du conteneur via connexion 'docker'
      ansible.builtin.raw: cat /etc/os-release
      # CRITIQUE : Changer l'hôte pour cibler le conteneur, et le type de connexion
      delegate_to: "{{ container_name }}"
      vars:
        ansible_connection: docker # Utilise le client Docker pour exécuter la commande
      register: os_info

    - name: Afficher les informations de la version du conteneur
      ansible.builtin.debug:
        msg: "Version de l'OS du conteneur : {{ os_info.stdout_lines }}"

    - name: 4. Supprimer le conteneur de test (Nettoyage)
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent