---
- name: Create MOTD file
  hosts: all
  become: true
  vars:
      text_message: "{{ ansible_host }}"
      my_name: "Virgile"
  tasks:
    - name: copy template file
      template:
        src: motd.j2
        dest: /etc/motd
  tags:
    - motd_config




