---
- hosts: 1.home
  tasks:
  - name: get a token
    ansible.builtin.command: openssl genrsa -out Dev.key 2048
  - name: read file
    ansible.builtin.shell: cat Dev.key
    register: my_token
  - name: get a hash
    ansible.builtin.shell: echo {{ '12345678' | hash('md5') }}
    register: my_hash
  - name: add new node into runtime inventory
    ansible.builtin.add_host:
       name: "dummy"
       token: "{{ my_token.stdout }}"
       hash:  "{{ my_hash.stdout }}"
       ip_address: "192.168.1.106"

- hosts: 2.home
  tasks:
    - name: if exist delete file
      ansible.builtin.file: path=/tmp/values state=absent
    - name: create a file
      ansible.builtin.file: path=/tmp/values state=touch
    - name: add values
      ansible.builtin.blockinfile:
        path: /tmp/values
        block: |
          {{hostvars['dummy']['token']}}
          {{hostvars['dummy']['hash']}}
          {{hostvars['dummy']['ip_address']}}

